IS_VISUAL_WORD_PROMPT = """You will be presented with a word and asked to determine if it can
be straightforwardly generated ("drawn") by a text-to-image model like Stable Diffusion, DALL-E,
or Midjourney.

Examples by category:

Physical Things; these are usually "drawable":
- "apple" -> clear round fruit shape -> <answer>yes</answer>
- "book" -> rectangular object with pages -> <answer>yes</answer>
- "breeze" -> just draw some flowy lines -> <answer>yes</answer>
- "mixer" -> just draw kitchen appliance with beaters -> <answer>yes</answer>

Actions; these are sometimes "drawable", usually correlated with how common and physical:
- "running" -> figure in motion -> <answer>yes</answer>
- "sleeping" -> figure lying with 'Z's -> <answer>yes</answer>

Abstract/Concepts; these are usually not drawable, unless they have a known symbol:
- "hello" -> not visually representable -> <answer>no</answer>
- "freedom" -> too abstract to draw directly -> <answer>no</answer>
- "peace" -> well known symbol -> <answer>yes</answer>
- "sadness" -> a :( smiley face -> <answer>yes</answer>

Properties; these are a mixed bag, some are "drawable", some are not:
- "red" -> color requires context -> <answer>no</answer>
- "big" -> relative concept, needs reference -> <answer>no</answer>
- "triangular" -> clear shape, draw a triangle can be drawn -> <answer>yes</answer>
- "spherical" -> clear shape, draw a circle -> <answer>yes</answer>
- "spiky" -> clear shape, draw a spiky object -> <answer>yes</answer>
- "angular" -> clear description, draw an angular object -> <answer>yes</answer>
- "slouched" -> just draw a person slouching -> <answer>yes</answer>

Heuristic 1: Could a person draw this word AND have another person recognize what was drawn?
Heuristic 2: Don't overthink it! If you can't imagine a simple drawing, it's probably not a "drawable" word. Likewise, if you can easily imagine a simple drawing, even if its not a 100% match with the word, then it's likely a "drawable" word.
Heuristic 4: Somethings are hard to visualize without also visualizing other things. You should lean towards "no" for these.
Heuristic 3: If unsure, lean towards "no".
Heuristic 4: Focus on the "straightforwardly" -- the word should be representable in a simple, direct way. As soon as there are several elements the scene, it's probably not "drawable".
Heuristic 5: If the word is unlikely to be captured in a photograph, it's probably not "drawable".
Heuristic 6: Think of the process of prompting the text-to-image model to generate the word down the line. Do you expect it to be easy to generate an undeniable representation of the word?

Note 1: if the word has multiple meanings, it's enough if even just one of them is "drawable", as long as it's a relatively common meaning.
Note 2: DO NOT WORRY ABOUT AMBIGUOUS DRAWINGS. It's enough for a viewer to straightforwardly agree that the drawing is a reasonable representation of the word. This does not exclude that the drawing may represent other words as well.
Note 3: Dynamic scenes or actions are generally not easily "drawable", especially if they do not involve people doing very common actions such as "running".
Note 4: If the drawing would depend on drawing arrows or other point-to-point indicators, it's probably not a "drawable" word.

Given the above, can the word "{word}" be straightforwardly be generated by a text-to-image model?

Provide brief reasoning, then your answer in XML tags: <answer>yes</answer> or <answer>no</answer>"""

